name: first workflow
on: workflow_dispatch
#on: Push
jobs:
  first-job:
    runs-on: ubuntu_latest
    steps:
      #- name: print greeting
        #run: |
         # echo "hello man"
          #echo "second line"
      - name: gat_job
        uses: actions/checkout@v4
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm help
      
