name: practice Project 1
#on: [push, workflow_dispatch] # Events
on: 
    push:
        branches:
            - main
            - 'dev_*' #using * meany any character other tha '/'
            - 'feat/**' # uning ** meanin inclusing '/'
        paths-ignore:
            - '.gitbub/workflow/**' # ignore this path when push the code
jobs:
    test:
        runs-on: ubuntu-latest # Runners
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: install nodejs
          uses: actions/setup-node@v4
          with:
            node-version: '14'
        - name: install dependencies
          run: npm ci
        - name: Run Test
          run: |
                npm help
                npm run test
    build:
        needs: test #depends on the above job
        runs-on: ubuntu-latest
        outputs:
          script-file: ${{steps.publish.outputs.script-file}} # reference the output of script file
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: install nodejs
          uses: actions/setup-node@v4
          with:
            node-version: '14'
        - name: install dependencies
          run: npm ci
        - name: Run build
          run: npm run build
        - name: upload artifacts 
          uses: actions/upload-artifact@v4 #upload artifacts to github
          with:
            name: dist-file
            path: | 
                dist
                package.json
        - name: Publish JS File
          id: publish
          run : find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';' # get the filename to use in nxt step deploy


    deploy:
        needs: build #depends on the above job
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: install nodejs
          uses: actions/setup-node@v4
          with:
            node-version: '14'
        - name: install dependencies
          run: npm ci
        - name: download Artifacts
          uses: actions/download-artifact@v4 # used the uploaded artifacts to the code
          with:
            name: dist-file
        - name: Output Contexts
          run: echo "${{needs.build.outputs.script-file}}" # reference to the above build process
        - name: Build Project
          run: |
                ls
                echo "Deploying......"
        
        


    