name: practice Project 1
#on: [push, workflow_dispatch] # Events
on: 
    push:
        branches:
            - main
            - 'dev_*' #using * meany any character other tha '/'
            - 'feat/**' # uning ** meanin inclusing '/'
        paths-ignore:
            - '.gitbub/workflow/**' # ignore this path when push the code
jobs:
    test:
        runs-on: ubuntu-latest # Runners
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: install nodejs
          uses: actions/setup-node@v4
          with:
            node-version: '14'
        - name: install dependencies
          run: npm ci
        - name: Run Test
          run: |
                npm help
                npm test
    build:
        needs: test #depends on the above job
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: install nodejs
          uses: actions/setup-node@v4
          with:
            node-version: '14'
        - name: install dependencies
          run: npm ci
        - name: Run build
          run: npm build
        - name: upload artifacts 
          uses: actions/upload-artifact@v4 #upload artifacts to github
          with:
            name: dist-file
            path: | 
                dist
                package.json

    deploy:
        needs: build #depends on the above job
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: install nodejs
          uses: actions/setup-node@v4
          with:
            node-version: '14'
        - name: install dependencies
          run: npm ci
        - name: download Artifacts
          uses: actions/download-artifact@v4 # used the uploaded artifacts to the code
          with:
            name: dist-file
        - name: Build Project
          run: |
                ls
                echo "Deploying......"
        
        


    